version: '3.8'

services:
    backend:
        container_name: 'api'
        build:
            dockerfile: Dockerfile
            context: .
        env_file: .env.docker
        ports:
            - '8080:8080'
        volumes:
            - ./:/home/app:cached
            - ./package.json:/home/app/package.json:cached
        depends_on:
            database:
                condition: service_healthy
        networks:
            - solutis_network

    database:
        image: postgres:14.4-alpine
        container_name: solutis-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: solutis-db
        ports:
            - 5432:5432
        networks:
            - solutis_network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        image: redis:latest
        container_name: api-redis
        restart: always
        command: redis-server --requirepass docker
        ports:
            - '6379:6379'
        depends_on:
            - backend
        networks:
            - solutis_network

    redis-insight:
        image: redislabs/redisinsight:latest
        container_name: api-redis-insight
        restart: always
        ports:
            - '5540:5540'
        depends_on:
            - redis
        networks:
            - solutis_network

networks:
    solutis_network:
