export enum ConstantsEnum {
	DATABASE = 'DATABASE',
	HASH_HELPER = 'HASH_HELPER',
	JWT_HELPER = 'JWT_HELPER',
	AUTH_GUARD = 'AUTH_GUARD',
	JWT_SERVICE = 'JWT_SERVICE',
	CACHE_HELPER = 'CACHE_HELPER',
	REDIS_SERVICE = 'REDIS_SERVICE',
}
